# Project information
site_name: Programming Guide
site_url: https://wonder-works-studio.github.io/Programming-Guide/
site_author: Joshua Mixon
site_description: Site is meant to serve as documentation for programmers at Wonder Works Studio.

# Repository
repo_name: Wonder-Works-Studio/Programming-Guide
repo_url: https://github.com/Wonder-Works-Studio/Programming-Guide

theme:
  #logo: "img/logo.png"
  #favicon: "img/favicon.png"
  name: material
  font:
    text: Ubuntu
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
  highlightjs: true
  hljs_languages:
    - lua

extra:
  #social:
  #  - icon: fontawesome/brands/github-alt
   #   link: https://github.com/Sleitnick/Knit
    #  name: GitHub repository for Knit
    #- icon: fontawesome/brands/twitter
      #link: https://twitter.com/sleitnick
      #name: Twitter for Knit's author

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true